# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Astro
featured: false
_inputs:
  title:
    type: text
    label: 'Title'
  pubDatetime:
    type: datetime
    label: 'Date Posted'
  description:
    type: text
    label: 'Description'
  postSlug:
    type: text
    label: 'Slug'
  tags:
    type: array
    label: 'Tags'
  featured:
    type: switch
    label: 'Featured'
  draft:
    type: switch
    label: 'Draft'
  ogImage:
    type: image
    label: 'OG Image'

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  posts:
    path: 'content/blog'
    parser: 'front-matter'

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source: 'src'

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: ''
  collections: ''
  layouts: null
  static: ''
  uploads: public

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Asia/Tokyo
